# Generated by Django 4.0.2 on 2022-02-05 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_investigation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Specialty', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MedicalComplaint', models.TextField()),
                ('ConsultationDate', models.DateTimeField()),
                ('ConsultationDoctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.doctors')),
                ('Investigations', models.ManyToManyField(to='app.Investigation')),
                ('MedicalSpecialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.medicalspecialty')),
            ],
        ),
    ]
