# Generated by Django 4.0.2 on 2022-02-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_medicalspecialty_doctors_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
