# Generated by Django 4.0.2 on 2022-02-06 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_patient_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='ConsultationDoctor',
        ),
    ]
